//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchScript.Compiler.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompilerNotes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompilerNotes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchScript.Compiler.Resources.Messages.CompilerNotes", typeof(CompilerNotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string N0 {
            get {
                return ResourceManager.GetString("N0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum value type was set here.
        /// </summary>
        internal static string N1 {
            get {
                return ResourceManager.GetString("N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the enum entry was declared here.
        /// </summary>
        internal static string N2 {
            get {
                return ResourceManager.GetString("N2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the event was declared here.
        /// </summary>
        internal static string N3 {
            get {
                return ResourceManager.GetString("N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the identifier was claimed here.
        /// </summary>
        internal static string N4 {
            get {
                return ResourceManager.GetString("N4", resourceCulture);
            }
        }
    }
}
