//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchScript.Compiler.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompilerErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompilerErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchScript.Compiler.Resources.Messages.CompilerErrors", typeof(CompilerErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string E0 {
            get {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ICE) expected value, got null.
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return cannot be used in non-function contexts.
        /// </summary>
        internal static string E10 {
            get {
                return ResourceManager.GetString("E10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot return a value of unknown type.
        /// </summary>
        internal static string E11 {
            get {
                return ResourceManager.GetString("E11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no functions with the name &quot;{0}&quot; are defined.
        /// </summary>
        internal static string E12 {
            get {
                return ResourceManager.GetString("E12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function &quot;{0}&quot; is not defined.
        /// </summary>
        internal static string E13 {
            get {
                return ResourceManager.GetString("E13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected a value, but the function &quot;{0}&quot; doesn&apos;t return one.
        /// </summary>
        internal static string E14 {
            get {
                return ResourceManager.GetString("E14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected a statement here.
        /// </summary>
        internal static string E15 {
            get {
                return ResourceManager.GetString("E15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected an expression here.
        /// </summary>
        internal static string E16 {
            get {
                return ResourceManager.GetString("E16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute &quot;{0}&quot; does not exist.
        /// </summary>
        internal static string E17 {
            get {
                return ResourceManager.GetString("E17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function arguments cannot be assigned to a new value in an inlined function.
        /// </summary>
        internal static string E18 {
            get {
                return ResourceManager.GetString("E18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no entry with the name &quot;{0}&quot; in the &quot;{1}&quot; enum is defined.
        /// </summary>
        internal static string E19 {
            get {
                return ResourceManager.GetString("E19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected {0}, got {1}.
        /// </summary>
        internal static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no property &quot;{0}&quot; is defined for type &quot;{1}&quot;.
        /// </summary>
        internal static string E20 {
            get {
                return ResourceManager.GetString("E20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum entry &quot;{0}&quot; has already been declared earlier.
        /// </summary>
        internal static string E3 {
            get {
                return ResourceManager.GetString("E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all entries in a non-numeric enum must be initialized with a value.
        /// </summary>
        internal static string E4 {
            get {
                return ResourceManager.GetString("E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event &quot;{0}&quot; has already been declared earlier.
        /// </summary>
        internal static string E5 {
            get {
                return ResourceManager.GetString("E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identifier &quot;{0}&quot; has already been claimed earlier.
        /// </summary>
        internal static string E6 {
            get {
                return ResourceManager.GetString("E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown identifier &quot;{0}&quot;.
        /// </summary>
        internal static string E7 {
            get {
                return ResourceManager.GetString("E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable &quot;{0}&quot; is not defined.
        /// </summary>
        internal static string E8 {
            get {
                return ResourceManager.GetString("E8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the type of function&apos;s argument &quot;{0}&quot; must be defined manually as it couldn&apos;t be understood from the implementation.
        /// </summary>
        internal static string E9 {
            get {
                return ResourceManager.GetString("E9", resourceCulture);
            }
        }
    }
}
