//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchScript.Compiler.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompilerErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompilerErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchScript.Compiler.Resources.Messages.CompilerErrors", typeof(CompilerErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string E0 {
            get {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ICE) expected value, got null.
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected {0}, got {1}.
        /// </summary>
        internal static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum entry &quot;{0}&quot; has already been declared earlier.
        /// </summary>
        internal static string E3 {
            get {
                return ResourceManager.GetString("E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all entries in a non-numeric enum must be initialized with a value.
        /// </summary>
        internal static string E4 {
            get {
                return ResourceManager.GetString("E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event &quot;{0}&quot; has already been declared earlier.
        /// </summary>
        internal static string E5 {
            get {
                return ResourceManager.GetString("E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identifier &quot;{0}&quot; has already been claimed earlier.
        /// </summary>
        internal static string E6 {
            get {
                return ResourceManager.GetString("E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown identifier &quot;{0}&quot;.
        /// </summary>
        internal static string E7 {
            get {
                return ResourceManager.GetString("E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable &quot;{0}&quot; is not defined.
        /// </summary>
        internal static string E8 {
            get {
                return ResourceManager.GetString("E8", resourceCulture);
            }
        }
    }
}
